### ISSUE TITLE
May I ask for explanation for the data format and how it should be implemented?

### ISSUE THREAD

**Issue by rokrokss** [jacobkrantz/ProbSyllabifier#7]
I'm fascinated with this work of yours
I want to try it, but I think it needs not-empty wordforms.db I guess?
I will be grateful if you can provide the dataset or how to build it.

**Comment by rokrokss** [comment]
I guess it's WebCelex where I can get the similar database, can you show me the settings that needed for your project?

**Comment by jacobkrantz** [comment]
Thanks for your interest in the project, @q0115643 !
We have added the [wordforms.db](../blob/master/wordforms.db) file to the project so everything should run the same for you as it does for us. If you have any questions, don't be afraid to ask.
Best,
Jacob
